// @ts-nocheck
import { Link, createFileRoute } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Reveal } from "@/components/site/Reveal";
import { guestsQuery } from "@/lib/queries";
export const Route = createFileRoute("/guests")({ loader: ({ context }) => context.queryClient.ensureQueryData(guestsQuery), component: Guests });
function Guests() { const { data } = useSuspenseQuery(guestsQuery); const [term,setTerm]=useState(""); const guests=useMemo(()=>data.guests.filter(g=>`${g.name} ${g.role||""} ${g.short_bio||""}`.toLowerCase().includes(term.toLowerCase())),[data,term]); return <div className="container-editorial py-14 md:py-20"><Reveal><p className="eyebrow">The people</p><h1 className="mt-4 text-[clamp(2.8rem,7vw,5rem)] uppercase">Guests &<br/>conversations.</h1><p className="mt-5 max-w-xl text-lg text-muted-foreground">People who have joined the Next Step conversation.</p></Reveal><div className="relative mt-10 max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input value={term} onChange={e=>setTerm(e.target.value)} className="pl-9" placeholder="Find a guest" /></div>{guests.length ? <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{guests.map((g,i)=><Reveal key={g.id} delay={i*60}><article className="group"><div className="aspect-[4/5] overflow-hidden rounded-lg border border-border bg-cream">{g.image_url?<img src={g.image_url} alt={g.name} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/>:<span className="flex h-full items-center justify-center text-display text-5xl text-foreground/15">{g.name.slice(0,2)}</span>}</div><h2 className="mt-4 text-2xl">{g.name}</h2>{g.role&&<p className="text-primary">{g.role}</p>}{g.short_bio&&<p className="mt-2 text-sm text-muted-foreground">{g.short_bio}</p>}<div className="mt-3 text-sm">{data.episodes.filter(e=>e.guest_id===g.id).map(e=><Link key={e.id} className="mr-3 text-primary underline" to="/episodes/$slug" params={{slug:e.slug}}>{e.title}</Link>)}</div></article></Reveal>)}</div>:<div className="mt-12 rounded-lg border border-dashed border-primary/50 p-10 text-center"><h2 className="text-2xl uppercase">No guests here yet.</h2><p className="mt-2 text-muted-foreground">Check back for the next conversation.</p></div>}</div>; }
