// @ts-nocheck
import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { AdminShell } from "./episodes";
type Guest={id:string;name:string;slug:string;role:string|null;short_bio:string|null;published:boolean};const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export const Route=createFileRoute("/admin/guests")({component:GuestsAdmin});
function GuestsAdmin(){const [rows,setRows]=useState<Guest[]>([]);const [edit,setEdit]=useState<Guest|null>(null);const [f,setF]=useState({name:"",slug:"",role:"",short_bio:""});const load=async()=>{const {data}=await supabase.from("guests").select("id,name,slug,role,short_bio,published").order("name");setRows((data||[]) as Guest[])};useEffect(()=>{load()},[]);async function save(e:React.FormEvent){e.preventDefault();const p={name:f.name,slug:f.slug||slugify(f.name),role:f.role||null,short_bio:f.short_bio||null};const {error}=edit?await supabase.from("guests").update(p).eq("id",edit.id):await supabase.from("guests").insert(p);if(error)return alert(error.message);setEdit(null);setF({name:"",slug:"",role:"",short_bio:""});load()}return <AdminShell title="Guests"><div className="grid gap-8 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{rows.map(r=><div key={r.id} className="surface-card flex items-center justify-between rounded-lg p-4"><button className="text-left" onClick={()=>{setEdit(r);setF({name:r.name,slug:r.slug,role:r.role||"",short_bio:r.short_bio||""})}}><b>{r.name}</b><span className="ml-3 text-sm text-muted-foreground">{r.role||"No role added"}</span></button><Button size="sm" variant="outline" onClick={async()=>{await supabase.from("guests").update({published:!r.published}).eq("id",r.id);load()}}>{r.published?"Hide":"Publish"}</Button></div>)}</div><form onSubmit={save} className="surface-card h-fit rounded-lg p-5"><p className="eyebrow">{edit?"Editing":"New guest"}</p><div className="mt-4 space-y-3"><Field label="Name" value={f.name} onChange={v=>setF({...f,name:v,slug:edit?f.slug:slugify(v)})}/><Field label="Slug" value={f.slug} onChange={v=>setF({...f,slug:v})}/><Field label="Role (optional)" value={f.role} onChange={v=>setF({...f,role:v})}/><Label>Short bio (optional)</Label><Textarea value={f.short_bio} onChange={e=>setF({...f,short_bio:e.target.value})}/></div><Button className="mt-5 w-full">{edit?"Save guest":"Create guest"}</Button></form></div></AdminShell>};function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div><Label>{label}</Label><Input required={!label.includes("optional")} className="mt-1" value={value} onChange={e=>onChange(e.target.value)}/></div>}
