// @ts-nocheck
import { Link, createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowUpRight, LogOut } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/admin/")({component:Dashboard});
type Counts={episodes:number;guests:number;messages:number;subscribers:number};
function Dashboard(){const nav=useNavigate();const [counts,setCounts]=useState<Counts>();const [name,setName]=useState("");useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return nav({to:"/admin/login"});const {data:roles}=await supabase.from("user_roles").select("role").eq("user_id",user.id);if(!roles?.some(r=>r.role==="admin"))return nav({to:"/admin/login"});setName(user.email||"");const [e,g,m,n]=await Promise.all([supabase.from("episodes").select("id",{count:"exact",head:true}),supabase.from("guests").select("id",{count:"exact",head:true}),supabase.from("messages").select("id",{count:"exact",head:true}).eq("status","unread"),supabase.from("newsletter_subscribers").select("id",{count:"exact",head:true}).eq("active",true)]);setCounts({episodes:e.count||0,guests:g.count||0,messages:m.count||0,subscribers:n.count||0})})()},[nav]);return <div className="min-h-screen bg-background"><header className="border-b border-border bg-cream"><div className="container-editorial flex h-16 items-center justify-between"><Link to="/admin" className="text-display uppercase">Next Step <span className="text-primary">Admin</span></Link><Button size="sm" variant="outline" onClick={async()=>{await supabase.auth.signOut();nav({to:"/admin/login"})}}><LogOut className="mr-2 h-4 w-4"/>Sign out</Button></div></header><main className="container-editorial py-10"><p className="eyebrow">Welcome back</p><h1 className="mt-3 text-4xl uppercase">Content desk</h1><p className="mt-2 text-muted-foreground">Signed in as {name}</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Episodes",counts?.episodes,"/admin/episodes"],["Guests",counts?.guests,"/admin/guests"],["Unread messages",counts?.messages,"/admin/messages"],["Subscribers",counts?.subscribers,"/admin/settings"]].map(([label,value,to])=><Link key={label as string} to={to as "/admin/episodes"} className="surface-card rounded-lg p-5 hover:border-primary"><span className="text-sm text-muted-foreground">{label as string}</span><span className="mt-3 block text-display text-4xl">{value===undefined?"—":value as number}</span></Link>)}</div><div className="mt-10 grid gap-4 md:grid-cols-2"><AdminLink to="/admin/episodes" title="Manage episodes" text="Create, edit, publish and feature your conversations."/><AdminLink to="/admin/guests" title="Manage guests" text="Keep featured people and their profiles ready to reuse."/><AdminLink to="/admin/messages" title="Inbox" text="Review contact and guest suggestions."/><AdminLink to="/admin/settings" title="Site settings" text="Update brand copy, images and listening links."/></div></main></div>}
function AdminLink({to,title,text}:{to:"/admin/episodes"|"/admin/guests"|"/admin/messages"|"/admin/settings";title:string;text:string}){return <Link to={to} className="surface-card flex items-start justify-between rounded-lg p-6 hover:border-primary"><span><b className="text-xl">{title}</b><span className="mt-2 block text-muted-foreground">{text}</span></span><ArrowUpRight className="text-primary"/></Link>}
