// @ts-nocheck
import { Link, createFileRoute, notFound } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, ExternalLink } from "lucide-react";
import coverFallback from "@/assets/episode-placeholder.jpg";
import { AudioPlayer } from "@/components/site/AudioPlayer";
import { EpisodeCard } from "@/components/site/EpisodeCard";
import { Reveal } from "@/components/site/Reveal";
import { ShareButtons } from "@/components/site/ShareButtons";
import { episodeLabel, formatDate, formatDuration } from "@/lib/format";
import { episodeQuery } from "@/lib/queries";
export const Route = createFileRoute("/episodes/$slug")({ loader: async ({context,params})=>{const data=await context.queryClient.ensureQueryData(episodeQuery(params.slug));if(!data.episode)throw notFound();return data;}, component: Episode });
function Episode(){const {slug}=Route.useParams();const {data}=useSuspenseQuery(episodeQuery(slug));const e=data.episode!; const links=[['Spotify',e.spotify_url],['Apple Podcasts',e.apple_url],['YouTube',e.youtube_url],['Watch video',e.video_url]].filter((x):x is [string,string]=>!!x[1]); return <div className="container-editorial py-10 md:py-16"><Link to="/episodes" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="h-4 w-4"/> All episodes</Link><section className="mt-8 grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><Reveal><img src={e.cover_image_url||coverFallback} alt={`Cover artwork for ${e.title}`} className="aspect-square w-full rounded-lg border border-border object-cover" /></Reveal><Reveal delay={80}><p className="eyebrow">{e.episode_number!=null?episodeLabel(e.episode_number):"Next Step episode"}</p><h1 className="mt-4 text-[clamp(2.3rem,5vw,4.4rem)] uppercase">{e.title}</h1>{e.guest?.name&&<p className="mt-4 text-lg">with <b>{e.guest.name}</b></p>}<p className="mt-4 text-sm text-muted-foreground">{[formatDate(e.publication_date),formatDuration(e.duration_seconds),e.category].filter(Boolean).join(" · ")}</p><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">{e.description||e.short_description}</p><AudioPlayer className="mt-7" src={e.audio_url} title={e.title}/><div className="mt-5 flex flex-wrap gap-3">{links.map(([name,url])=><a key={name} href={url} target="_blank" rel="noreferrer noopener" className="inline-flex items-center gap-1 rounded-md border border-border px-4 py-2 text-sm font-semibold hover:border-primary hover:text-primary">{name}<ExternalLink className="h-3.5 w-3.5"/></a>)}</div><ShareButtons className="mt-6" title={e.title}/></Reveal></section>{e.tags.length>0&&<section className="mt-14 border-t border-border pt-8"><p className="eyebrow">Topics</p><div className="mt-3 flex flex-wrap gap-2">{e.tags.map(t=><span key={t} className="rounded-full bg-cream px-3 py-1 text-sm">{t}</span>)}</div></section>}{e.transcript&&<details className="mt-12 border-t border-border pt-8"><summary className="cursor-pointer text-2xl font-bold uppercase">Read transcript</summary><p className="mt-6 whitespace-pre-wrap leading-8 text-muted-foreground">{e.transcript}</p></details>}{data.related.length>0&&<section className="mt-16 border-t border-border pt-10"><h2 className="text-3xl uppercase">Keep listening</h2><div className="mt-8 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{data.related.map(r=><EpisodeCard key={r.id} episode={r}/>)}</div><Link to="/episodes" className="mt-8 inline-flex items-center gap-2 font-semibold text-primary">All episodes <ArrowRight className="h-4 w-4"/></Link></section>}</div>; }
